//
// Created by Hasaker on 2018/10/23.
//

#ifndef DATASTRUCTUREANDALGORITHM_LINEAR_DATA_STRUCTURE_H
#define DATASTRUCTUREANDALGORITHM_LINEAR_DATA_STRUCTURE_H

#endif //DATASTRUCTUREANDALGORITHM_LINEAR_DATA_STRUCTURE_H
